<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
    <DebugType>portable</DebugType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Crumpled.Nostalgid</Product>
    <PackageId>Crumpled.Nostalgid</PackageId>
    <Title>Crumpled.Nostalgid</Title>
    <Description>...</Description>
    <PackageTags>umbraco;umbraco-marketplace;nostalgid</PackageTags>
    <Authors>Crumpled Dog</Authors>
    <Company>Crumpled Dog</Company>
    <Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © Crumpled Dog</Copyright>
    <PackageProjectUrl>https://github.com/CrumpledDog/Crumpled.Nostalgid</PackageProjectUrl>
    <RepositoryUrl>https://github.com/CrumpledDog/Crumpled.Nostalgid</RepositoryUrl>
    <PackageReadmeFile>README_nuget.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>crumpled-nostalgid-icon.png</PackageIcon>
    <InformationalVersion>$(PackageVersion)</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="Umbraco.Cms.Web.Website" />
    <PackageReference Include="Umbraco.Cms.Web.Common" />
    <PackageReference Include="Umbraco.Cms.Api.Common" />
    <PackageReference Include="Umbraco.Cms.Api.Management" />
  </ItemGroup>
  
  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="..\..\docs\README_nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\docs\crumpled-nostalgid-icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

   <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>